@startuml class_diagram
' 多対多のクラス図の例

skinparam monochrome true
skinparam shadowing false

' クラスを定義
class 顧問{
    教師ID
    名前
}

class 部活{
    部活ID
    名前
}

class 生徒{
    学籍番号
    名前
}

' 関係を定義 
left to right direction
顧問 "1" --- "0...1" 部活
部活 "1...*" --- "1...*" 生徒

' umlの終了を宣言
@enduml