@startuml class_diagram
' 演習(部活動の管理)

' クラスを定義 
class 生徒{
    生徒ID
    性別
    氏名
    学年
}

class 教師{
    教師ID
    性別

}

class 部活{
    部活ID
    顧問
    部員
}

class 所属部活{
    部活名
}



' 関係を定義 
left to right direction
生徒 "1" --- "1...*" 所属部活
所属部活 "1" --- "1" 部活
部活 "0...1" --- "1" 顧問

' umlの終了を宣言
@enduml